### ISSUE TITLE
Please update and add support for fabric

### ISSUE THREAD

**Issue by ghost** [InferusAnima/AdvancementSync#1]
Please, could you keep updating this mod? It's the best and most recent one, or at list could you update it for the version 1.19.2 working with fabric, please?

**Comment by InferusAnima** [comment]
Hello, I could update it for 1.19.2, but for forge, I have no experience with fabric unfortunately.

**Comment by ghost** [comment]
Ok, thank you so much. I think it's time to switch to forge :)

**Comment by InferusAnima** [comment]
Updated in 0933f08
